openapi: 3.0.0
info:
  title: OLSS ActivityLog API
  description: OLSS ActivityLog REST API
  version: 1.0.0
security:
  - BearerAuth: []
paths:
  /v1.0/activitylogentries:
    get:
      tags:
        - ActivityLog
      description: |
        Search for activity log entries which match the specified search criteria.
        Query may include reserved characters, which need to be URL-encoded: plus sign (+), and square brackets ([]).
        Due to background indexing, new entries could take a few seconds before they appear in the search results.
      operationId: SearchActivityLog
      parameters:
        - name: offset
          in: query
          description: Number of entries to skip from the beginning of the response (does not affect `totalHits`).
          schema:
            minimum: 0
            default: 0
            type: integer
            format: int32
        - name: limit
          in: query
          description: Maximum number of entries to include in the response (does not affect `totalHits`).
          schema:
            minimum: 1
            maximum: 1000
            default: 50
            type: integer
            format: int32
        - name: timestamp
          in: query
          description: |
            Timestamp filter.
            Only entries submitted in the given time frame are returned.
            Format: `[DATETIME,DATETIME]`, where `DATETIME` is either `YYYY-MM-DDK`, `YYYY-MM-DDTHH:mm:ssK`, or `YYYY-MM-DDThh:mm:ss.fffK`.
            Default value is a one-week range ending at the moment of the request.
            Examples: `[2019-05-23Z,2019-05-30Z]`, `[2019-05-23T14:00:00+03:00,2019-05-23T23:00:00+03:00]`.
          schema:
            type: string
        - name: userApplication
          in: query
          description: |
            User-friendly name of an application (case-sensitive, exact match).
            If specified, only entries submitted by the given application are returned.
          schema:
            type: string
            maxLength: 50
        - name: eventLevel
          in: query
          description: |
            Event level filter (case-sensitive, exact match).
            If specified, only entries with the given event level are returned.
          schema:
            type: string
        - name: descriptionOrDetails
          in: query
          description: |
            Description/details filter (case-insensitive, set of prefixes).
            If specified, only entries containing words with all of the given prefixes in details or description, are returned.
            Exact definitions of "word" and "prefix" depend on the language of the value.
            For example, filter by `"inst error"` will include `"Instrument error"` and `"Error during installation"`, but not `"Error during uninstallation"`.
          schema:
            type: string
        - name: eventType
          in: query
          description: |
            Event type filter (case-sensitive, exact match).
            If specified, only entries with the given event type are returned.
          schema:
            type: string
        - name: user
          in: query
          description: |
            User filter (case-insensitive, set of prefixes).
            If specified, only entries corresponding to the user with the given prefixes, are returned.
            Exact definition of "prefix" depends on the language of the value.
            For example, filter by `"ja doe"` will include `"Jane Doe (MYCOMPANY\janedoe)"` and `"Doe, Jack (MYCOMPANY\jackdoe)"`, but not `"janedoe"`.
          schema:
            type: string
        - name: sort
          in: query
          description: "Sorting of the results (case-sensitive column name, optionally prefixed with a direction: `+` for ascending, `-` for descending)."
          schema:
            type: string
            default: "-timestamp"
            example: "+timestamp"
        - name: objectId
          in: query
          description: |
            Object filter.
            If specified, only entries corresponding to the object with the given ID are returned.
          schema:
            type: integer
            format: int32
        - name: onlyDeletedObjects
          in: query
          description: Filter by deleted objects. If `true`, only entries corresponding to the deleted objects are returned.
          schema:
            type: boolean
      responses:
        '200':
          description: Search response (results and total hits)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActivityLogSearchResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '../common.yml#/components/schemas/ApiError'
        '401':
          $ref: '../common.yml#/components/responses/Unauthenticated'
        '503':
          $ref: '../common.yml#/components/responses/ServiceUnavailable'
    post:
      tags:
        - ActivityLog
      description: Create a new activity log entry with the specified properties.
      operationId: PostActivityLog
      requestBody:
        x-name: activityLogEntry
        description: The data to put in the activity log entry
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ActivityLogEntry'
        required: true
        x-position: 1
      responses:
        '200':
          description: If the activity log is disabled, no activity log entry is created and OK is returned.
        '201':
          description: If the activity log is enabled and an entry is created successfully, Created is returned.
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '../common.yml#/components/schemas/ApiError'
        '401':
          description: 401 Unauthorized
          content:
            application/json:
              schema:
                $ref: '../common.yml#/components/schemas/ApiError'
              examples:
                noTokenExample:
                  $ref: '../common.yml#/components/examples/NoTokenErrorResponse'
                tokenEncodingExample:
                  $ref: '../common.yml#/components/examples/TokenEncodingErrorResponse'
                tokenSignatureExample:
                  $ref: '../common.yml#/components/examples/TokenSignatureErrorResponse'
        '415':
          description: 'Unsupported Media Type'
        '503':
          $ref: '../common.yml#/components/responses/ServiceUnavailable'
components:
  securitySchemes:
    BearerAuth:
      $ref: '../common.yml#/components/securitySchemes/BearerAuth'
  schemas:
    ActivityLogSearchResponse:
      type: object
      additionalProperties: false
      properties:
        results:
          type: array
          nullable: true
          items:
            $ref: '#/components/schemas/ActivityLogEntrySearchResult'
        totalHits:
          type: integer
          format: int32
        resultsLimitedByPermissions:
          type: boolean
          description: The flag indicates whether limitations in user permissions prevented seeing some or all Activity Log content.
    ActivityLogEntrySearchResult:
      allOf:
        - $ref: '#/components/schemas/ActivityLogEntry'
        - type: object
          additionalProperties: false
          properties:
            id:
              type: integer
              format: int32
            timestamp:
              type: string
              format: date-time
            objectDeleted:
              type: boolean
              nullable: true
            user:
              type: string
              nullable: true
    ActivityLogEntry:
      allOf:
        - $ref: '#/components/schemas/ActivityLogModelBase'
        - type: object
          additionalProperties: false
          required:
            - description
            - eventLevel
            - eventType
          properties:
            applicationDataReference:
              type: string
              nullable: true
            description:
              type: string
              minLength: 1
              maximum: 450
            details:
              type: string
              nullable: true
              maximum: 2000
            eventLevel:
              type: string
              example: Error
            eventType:
              type: string
              example: Instrument
            objectId:
              type: integer
              format: int32
              nullable: true
            sampleId:
              type: string
              nullable: true
              maximum: 255
            bufferingDelay:
              type: string
              nullable: true
              description: Time difference between ActivityLog creation and sending it to server. (ISO 8601)
              example: PT3H30M5S
    ActivityLogModelBase:
      type: object
      additionalProperties: false
      required:
        - userApplication
      properties:
        userApplication:
          type: string
          minLength: 1
          maximum: 50
        clientDevice:
          type: string
          maximum: 50